baseURL = 'https://fixie.ulynks.io/'
languageCode = 'en-us'
title = 'Fixie Agents by uLynks'
# theme = 'ananke'
theme = 'ulynks'

# Configure server
# https://gohugo.io/getting-started/configuration/#configure-server

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = "default-src 'self' https://api.fixie.ai https://cdn.jsdelivr.net https://embed.fixie.ai https://eu.umami.is https://fonts.gstatic.com https://fonts.googleapis.com"
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'

[params]
  subtitle = 'Growing on Fyn, Denmark 🇩🇰'
  umami = '3cf42fbf-5ff7-4ba7-b4d1-607641c5b4e8'
  mainWebsite = 'https://www.ulynks.io/'
  [params.contact]
    email = 'contact@ulynks.io'
    phone = ''

[[menus.main]]
name = 'Django'
url = '/django'
weight = 1

[[menus.main]]
name = 'Python'
url = '/python'
weight = 2

[[menus.main]]
name = 'Scopus'
pageRef = '/scopus'
weight = 3

[[menus.main]]
name = 'React'
pageRef = '/react'
weight = 4

[[menus.main]]
name = 'SDU'
pageRef = '/sdu'
weight = 5

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
