baseURL = 'https://fixie.ulynks.io/'
languageCode = 'en-us'
title = 'Fixie Agents by uLynks'
# theme = 'ananke'
theme = 'ulynks'

# Configure server
# - https://gohugo.io/getting-started/configuration/#configure-server
# - https://content-security-policy.com

[server]
[[server.headers]]
    for = '/**'
    [server.headers.values]
      Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://eu.umami.is https://api-gateway-eu.umami.dev;
      font-src https://fonts.gstatic.com;
      frame-src 'self' https://api.fixie.ai https://embed.fixie.ai;
      script-src 'self' https://cdn.jsdelivr.net https://eu.umami.is https://widget.reallywrite.com;
      style-src 'self' https://fonts.googleapis.com
      """
      Referrer-Policy = 'strict-origin-when-cross-origin'
      X-Content-Type-Options = 'nosniff'
      X-Frame-Options = 'DENY'
      X-XSS-Protection = '1; mode=block'

[params]
  subtitle = 'Growing on Fyn, Denmark 🇩🇰'
  umami = '3cf42fbf-5ff7-4ba7-b4d1-607641c5b4e8'
  mainWebsite = 'https://www.ulynks.io/'
  [params.contact]
    email = 'contact@ulynks.io'
    phone = ''

# [[menus.main]]
# name = 'Django'
# url = '/django'
# weight = 1
#
# [[menus.main]]
# name = 'Python'
# url = '/python'
# weight = 2
#
# [[menus.main]]
# name = 'Scopus'
# pageRef = '/scopus'
# weight = 3
#
# [[menus.main]]
# name = 'React'
# pageRef = '/react'
# weight = 4

[[menus.main]]
name = 'SDU'
pageRef = '/sdu'
weight = 5

[[menus.main]]
name = 'EARMA'
pageRef = '/earma'
weight = 6

# [[menus.main]]
# name = 'ReallyWrite'
# pageRef = '/really-write'
# weight = 7

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
