baseURL = 'https://www.ulynks.io/'
languageCode = 'en-us'
title = 'uLynks'
# theme = 'ananke'
theme = 'ulynks'

[params]
  subtitle = 'Growing on Fyn, Denmark 🇩🇰'
  umami = '3cf42fbf-5ff7-4ba7-b4d1-607641c5b4e8'
  [params.contact]
    email = 'contact@ulynks.io'
    phone = ''

[[menus.main]]
name = 'Django'
url = '/django'
weight = 1

[[menus.main]]
name = 'Python'
url = '/python'
weight = 2

[[menus.main]]
name = 'Scopus'
pageRef = '/scopus'
weight = 3

[[menus.main]]
name = 'React'
pageRef = '/react'
weight = 4

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
